/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 문장 뉘앙스 분석
         * @description Gemini 로 본음/건전, 정중도 점수, 리스크, 추천 답장을 분석한다.
         */
        post: operations["analyze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phrases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 모든 숙어 조회
         * @description DB에 저장된 모든 비즈니스 숙어를 정중도 순으로 조회
         */
        get: operations["getAllPhrases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phrases/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 상황별 숙어 검색
         * @description EMAIL, MEETING 등 특정 상황에 맞는 숙어만 필터링
         */
        get: operations["getPhrasesBySituation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAllHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteHistory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalyzeRequestDTO: {
            text: string;
            relationshipType?: string;
        };
        EvaluationDTO: {
            summary?: string;
            keigo_check?: boolean;
            cushion_phrase_check?: boolean;
        };
        FeedbackDTO: {
            issues?: string[];
            cultural_nuance?: string;
        };
        HonneDTO: {
            tatemae?: string;
            trueIntent?: string;
            actionItem?: string;
        };
        MetricsDTO: {
            /** Format: int32 */
            politeness?: number;
            /** Format: int32 */
            indirectness?: number;
            /** Format: int32 */
            etiquette?: number;
        };
        NuanceResponseDTO: {
            /** Format: int32 */
            totalScore?: number;
            category?: string;
            metrics?: components["schemas"]["MetricsDTO"];
            evaluation?: components["schemas"]["EvaluationDTO"];
            feedback?: components["schemas"]["FeedbackDTO"];
            suggestions?: components["schemas"]["SuggestionDTO"][];
            sentiment?: components["schemas"]["SentimentDTO"];
            riskAnalysis?: components["schemas"]["RiskAnalysisDTO"];
            smartReplies?: components["schemas"]["SmartReplyDTO"][];
        };
        RiskAnalysisDTO: {
            riskLevel?: string;
            redFlags?: string[];
            copingStrategy?: string;
        };
        SentimentDTO: {
            polarity?: string;
            /** Format: double */
            confidence?: number;
            honne?: components["schemas"]["HonneDTO"];
        };
        SmartReplyDTO: {
            scenario?: string;
            content?: string;
            description?: string;
            nuanceLevel?: string;
        };
        SuggestionDTO: {
            text?: string;
            level?: string;
        };
        BusinessPhrase: {
            /** Format: int64 */
            id?: number;
            phrase?: string;
            meaning?: string;
            situation?: string;
            /** Format: int32 */
            politenessLevel?: number;
            usageExample?: string;
        };
        AnalysisHistory: {
            /** Format: int64 */
            id?: number;
            userInput?: string;
            /** Format: int32 */
            totalScore?: number;
            category?: string;
            riskLevel?: string;
            fullAnalysisJson?: string;
            /** Format: date-time */
            createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NuanceResponseDTO"];
                };
            };
        };
    };
    getAllPhrases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BusinessPhrase"][];
                };
            };
        };
    };
    getPhrasesBySituation: {
        parameters: {
            query: {
                /** @description 검색할 상황 태그(예: EMAIL, MEETING) */
                situation: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BusinessPhrase"][];
                };
            };
        };
    };
    getAllHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnalysisHistory"][];
                };
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
    deleteHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
