/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/phrases/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 숙어 수정
         * @description 표현을 통째로 교체. 없는 id 면 404, 다른 행과 표현이 겹치면 409
         */
        put: operations["updatePhrase"];
        post?: never;
        /**
         * 숙어 삭제
         * @description 없는 id 면 404. 기본 사전(data.sql 시드)의 표현은 삭제해도 다음 부팅 때 다시 들어간다
         */
        delete: operations["deletePhrase"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phrases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 숙어 목록
         * @description 정중도 높은 순으로 한 페이지. 사용자가 추가한 표현까지 포함한다.
         */
        get: operations["getAllPhrases"];
        put?: never;
        /**
         * 숙어 추가
         * @description 새 표현을 사전에 등록. 이미 있는 표현이면 409
         */
        post: operations["createPhrase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 문장 뉘앙스 분석
         * @description Gemini 로 본음/건전, 정중도 점수, 리스크, 추천 답장을 분석한다.
         */
        post: operations["analyze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/phrases/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 상황별 숙어 검색
         * @description EMAIL, MEETING 등 특정 상황에 맞는 숙어만 필터링. 허용되지 않은 값이면 400
         */
        get: operations["getPhrasesBySituation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 분석 이력 목록
         * @description 최신순 요약 목록. 저장된 분석 결과 전체는 포함되지 않는다 — 한 건을 펼칠 때 상세 조회를 쓴다.
         */
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 분석 이력 상세
         * @description 저장된 분석 결과 전체(fullAnalysisJson)를 포함한 한 건.
         */
        get: operations["getHistoryDetail"];
        put?: never;
        post?: never;
        /** 분석 이력 삭제 */
        delete: operations["deleteHistory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PhraseRequestDTO: {
            phrase: string;
            meaning: string;
            /** @enum {string} */
            situation?: "EMAIL" | "MEETING" | "INTERVIEW" | "NEGOTIATION" | "CONFIRMATION" | "REQUEST" | "NOTIFICATION" | "CUSHION";
            /** Format: int32 */
            politenessLevel?: number;
            usageExample?: string;
        };
        BusinessPhrase: {
            /** Format: int64 */
            id?: number;
            phrase?: string;
            meaning?: string;
            /** @enum {string} */
            situation?: "EMAIL" | "MEETING" | "INTERVIEW" | "NEGOTIATION" | "CONFIRMATION" | "REQUEST" | "NOTIFICATION" | "CUSHION";
            /** Format: int32 */
            politenessLevel?: number;
            usageExample?: string;
        };
        AnalyzeRequestDTO: {
            text: string;
            relationshipType?: string;
        };
        EvaluationDTO: {
            summary?: string;
            keigo_check?: boolean;
            cushion_phrase_check?: boolean;
        };
        FeedbackDTO: {
            issues?: string[];
            cultural_nuance?: string;
        };
        HonneDTO: {
            tatemae?: string;
            trueIntent?: string;
            actionItem?: string;
        };
        MetricsDTO: {
            /** Format: int32 */
            politeness?: number;
            /** Format: int32 */
            indirectness?: number;
            /** Format: int32 */
            etiquette?: number;
        };
        NuanceResponseDTO: {
            /** Format: int32 */
            totalScore?: number;
            category?: string;
            metrics?: components["schemas"]["MetricsDTO"];
            evaluation?: components["schemas"]["EvaluationDTO"];
            feedback?: components["schemas"]["FeedbackDTO"];
            suggestions?: components["schemas"]["SuggestionDTO"][];
            sentiment?: components["schemas"]["SentimentDTO"];
            riskAnalysis?: components["schemas"]["RiskAnalysisDTO"];
            smartReplies?: components["schemas"]["SmartReplyDTO"][];
        };
        RiskAnalysisDTO: {
            riskLevel?: string;
            redFlags?: string[];
            copingStrategy?: string;
        };
        SentimentDTO: {
            polarity?: string;
            /** Format: double */
            confidence?: number;
            honne?: components["schemas"]["HonneDTO"];
        };
        SmartReplyDTO: {
            scenario?: string;
            content?: string;
            description?: string;
            nuanceLevel?: string;
        };
        SuggestionDTO: {
            text?: string;
            level?: string;
        };
        PageResponseBusinessPhrase: {
            content?: components["schemas"]["BusinessPhrase"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            hasNext?: boolean;
        };
        AnalysisHistorySummaryDTO: {
            /** Format: int64 */
            id?: number;
            userInput?: string;
            /** Format: int32 */
            totalScore?: number;
            category?: string;
            riskLevel?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        PageResponseAnalysisHistorySummaryDTO: {
            content?: components["schemas"]["AnalysisHistorySummaryDTO"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            hasNext?: boolean;
        };
        AnalysisHistory: {
            /** Format: int64 */
            id?: number;
            userInput?: string;
            /** Format: int32 */
            totalScore?: number;
            category?: string;
            riskLevel?: string;
            fullAnalysisJson?: string;
            /** Format: date-time */
            createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updatePhrase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhraseRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BusinessPhrase"];
                };
            };
        };
    };
    deletePhrase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAllPhrases: {
        parameters: {
            query?: {
                /** @description 0부터 시작하는 페이지 번호 */
                page?: number;
                /** @description 페이지 크기 (최대 100) */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseBusinessPhrase"];
                };
            };
        };
    };
    createPhrase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PhraseRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BusinessPhrase"];
                };
            };
        };
    };
    analyze: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequestDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NuanceResponseDTO"];
                };
            };
        };
    };
    getPhrasesBySituation: {
        parameters: {
            query: {
                /** @description 검색할 상황 태그(예: EMAIL, MEETING) */
                situation: "EMAIL" | "MEETING" | "INTERVIEW" | "NEGOTIATION" | "CONFIRMATION" | "REQUEST" | "NOTIFICATION" | "CUSHION";
                /** @description 0부터 시작하는 페이지 번호 */
                page?: number;
                /** @description 페이지 크기 (최대 100) */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseBusinessPhrase"];
                };
            };
        };
    };
    getHistory: {
        parameters: {
            query?: {
                /** @description 0부터 시작하는 페이지 번호 */
                page?: number;
                /** @description 페이지 크기 (최대 100) */
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAnalysisHistorySummaryDTO"];
                };
            };
        };
    };
    getHistoryDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AnalysisHistory"];
                };
            };
        };
    };
    deleteHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: Record<string, never>;
                    };
                };
            };
        };
    };
}
